input {
    stdin {
    }
    jdbc {
                jdbc_connection_string => "jdbc:mysql://HOST_IP:3306/middleground?allowLoadLocalInfile=false&autoDeserialize=false&serverTimezone=Asia/Shanghai&useSSL=false"
                jdbc_user => "root"
                jdbc_password => "middleground2022"
                jdbc_default_timezone => "Asia/Shanghai"
                jdbc_driver_library => "/usr/share/logstash/mysql-connector-java-5.1.47.jar"
                jdbc_driver_class => "com.mysql.jdbc.Driver"
                jdbc_paging_enabled => "true"
                jdbc_page_size => "10000"
                schedule => "* * * * *"
                statement => "SELECT * from stbz_goods_goods  where updated_time > UNIX_TIMESTAMP(:sql_last_value)"
                record_last_run => true
                clean_run => true
                tracking_column_type => "timestamp"
                use_column_value => false
                tracking_column => "updated_time"
                type => "goods"
   }

}


filter {
	ruby {
		code => "event.set('timestamp', event.get('@timestamp').time.localtime + 8*60*60)"
	}
	ruby {
		code => "event.set('@timestamp',event.get('timestamp'))"
	}

      	mutate{
  		add_field =>{
  		"[my_join_field][name]"=>"goods"
                }
	}
         
       	mutate {
	    	remove_field => [ "@timestamp","@version","psoriasis","goods_type"]
	}	
}


output{
     elasticsearch {
             hosts => ["HOST_IP:9200"]
             index => "private_index"
             password => "middleground2022"
             user => "elastic"
             document_id => "goods_%{id}"
             document_type => "_doc"
     }
    stdout {
        codec => json_lines
    }
}
