server {
        listen       80;
        server_name  agent.domain_name;
        index index.html index.htm index.php;

        root /data/project/front/agent;

        error_log 	/var/log/nginx/agen.error.log;
        access_log 	/var/log/nginx/agent.access.log;


        location / {
            index  index.html index.htm;
            try_files $uri $uri/ @router; # 需要指向下面的@router否则会出现vue的路由在nginx中刷新出现404
          }

          location @router {
            rewrite ^.*$ /index.html last;
          }


        location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
        {
            expires      30d;
        }

        location ~ .*\.(js|css)?$
        {
            expires      12h;
        }

        location ~ /.well-known {
            allow all;
        }

        location ~ /\.
        {
            deny all;
        }

}
