server
    {
	# listen 443 ssl;
	#ssl_certificate /usr/local/nginx 
	#ssl_certificate_key /usr/local/nginx 
	listen 80;
	server_name api.domain_name;
	index index.html index.htm index.php default.html default.htm default.php;

	location / {
		proxy_pass http://HOST_IP:8199/;
	}
	
	access_log  /var/log/nginx/api.log;
}

