server {
	listen  80;
	server_name  download.domain_name;
	index index.html index.htm index.php;
	root /data/project/backend/download;
	error_log	/var/log/nginx/download.error.log;
	access_log	/var/log/nginx/download.access.log;

	location / {
	    root /data/project/backend/download;
	    index  index.html index.htm;
	    try_files $uri $uri/ @router; # 需要指向下面的@router否则会出现vue的路由在nginx中刷新出现404
	  }

	location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
	{
	    expires      30d;
	}

	location ~ .*\.(js|css)?$
	{
	    expires      12h;
	}

	location ~ /.well-known {
	    allow all;
	}

	location ~ /\.
	{
	    deny all;
	}

}

