server {
	listen       80;
	server_name  scm.domain_name;
	index index.html index.htm index.php;
	root /data/project/front/scm;
	error_log 	/var/log/nginx/scm.error.log;
  	access_log 	/var/log/nginx/scm.access.log;

	location / {
		index  index.html index.htm;
		try_files $uri $uri/ @router; # 需要指向下面的@router否则会出现vue的路由在nginx中刷新出现404
	}
         
	location @router {
		rewrite ^.*$ /index.html last;
	}

	location /pxh/ {
	    index index.html index.htm;
	    try_files $uri $uri/ /pxh/index.html ;
	}

	location ~^/(api|v2)/ {
	    proxy_pass http://HOST_IP:6666;
        proxy_set_header Host $host;
	    proxy_buffering off;
	    proxy_set_header X-Real-IP $remote_addr;
	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}

	location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
        {
	    expires      30d;
        }

	location ~ .*\.(js|css)?$
        {
	    expires      12h;
        }

	location ~ /.well-known {
	    allow all;
        }

	location ~ /\.
        {
	    deny all;
        }

}
