server
    {
	listen 80;
	server_name sso.domain_name;
	index index.html index.htm index.php default.html default.htm default.php;
	root  /data/project/backend/public;

	location / {
		root /data/project/backend/public;
	#proxy_pass http://HOST_IP:8199/;
	}

	location ~^/(sso|common) {
		proxy_pass http://HOST_IP:8199;
	}
	access_log   /var/log/nginx/sso.log;
}
