server {
	listen	80;
	server_name  www.domain_name;
	index index.htm index.html index.php;
	root /data/project/backend/public;
	error_log  /var/log/nginx/www.error.log;
  	access_log  /var/log/nginx/www.access.log;

	location ^~ /aboutus {
		proxy_pass http://HOST_IP:8199/web/aboutus;
		proxy_set_header Host $host;
		proxy_buffering off;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}

	location ^~ /news {
		proxy_pass http://HOST_IP:8199/web/news;
		proxy_set_header Host $host;
		proxy_buffering off;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}

	location = /  {
		proxy_pass http://HOST_IP:8199/web/index;
		proxy_set_header Host $host;
		proxy_buffering off;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}

	location  /  {
		proxy_pass http://HOST_IP:8199;
		proxy_set_header Host www.jxhh.com;
		proxy_buffering off;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
	
	location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
	{
		expires      30d;
	}

	location ~ .*\.(js|css)?$
	{
		expires      12h;
	}

	location ~ /.well-known {
		allow all;
	}

	location ~ /\.
	{
		deny all;
	}

}
